# Generated by Django 4.0 on 2023-06-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernote',
            old_name='support',
            new_name='call_type',
        ),
    ]
