# Generated by Django 4.0 on 2023-06-29 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_support_usernote_call_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernote',
            old_name='code',
            new_name='user',
        ),
    ]
